export const NOTIFICATION_ERROR_CODES = {
    NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
    INVALID_NOTIFICATION_DATA: "INVALID_NOTIFICATION_DATA",
    NOTIFICATION_CREATION_FAILED: "NOTIFICATION_CREATION_FAILED",
    NOTIFICATION_UPDATE_FAILED: "NOTIFICATION_UPDATE_FAILED",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    FORBIDDEN_ACCESS: "FORBIDDEN_ACCESS",
    SERVER_ERROR: "SERVER_ERROR",
    DATABASE_EXCEPTION: "DATABASE_EXCEPTION",
    ERROR_FETCHING_NOTIFICATION: "ERROR_FETCHING_NOTIFICATION",
};

export const NOTIFICATION_ERROR_MESSAGES = {
    [NOTIFICATION_ERROR_CODES.NOTIFICATION_NOT_FOUND]: "Notification with the given ID does not exist.",
    [NOTIFICATION_ERROR_CODES.INVALID_NOTIFICATION_DATA]: "The provided notification data is invalid. Please check the fields and try again.",
    [NOTIFICATION_ERROR_CODES.NOTIFICATION_CREATION_FAILED]: "An error occurred while creating the notification. Please try again later.",
    [NOTIFICATION_ERROR_CODES.NOTIFICATION_UPDATE_FAILED]: "An error occurred while updating the notification. Please try again later.",
    [NOTIFICATION_ERROR_CODES.UNAUTHORIZED_ACCESS]: "User is not authenticated. Please log in to continue.",
    [NOTIFICATION_ERROR_CODES.FORBIDDEN_ACCESS]: "User does not have permission to access this notification.",
    [NOTIFICATION_ERROR_CODES.SERVER_ERROR]: "An unexpected error occurred. Please try again later.",
    [NOTIFICATION_ERROR_CODES.DATABASE_EXCEPTION]: "A database error occurred. Please try again later.",
    [NOTIFICATION_ERROR_CODES.ERROR_FETCHING_NOTIFICATION]: "An error occurred while fetching notification details. Please try again later.",
};

export const NOTIFICATION_ERROR_STATUS = {
    [NOTIFICATION_ERROR_CODES.NOTIFICATION_NOT_FOUND]: 404,
    [NOTIFICATION_ERROR_CODES.INVALID_NOTIFICATION_DATA]: 400,
    [NOTIFICATION_ERROR_CODES.NOTIFICATION_CREATION_FAILED]: 500,
    [NOTIFICATION_ERROR_CODES.NOTIFICATION_UPDATE_FAILED]: 500,
    [NOTIFICATION_ERROR_CODES.UNAUTHORIZED_ACCESS]: 401,
    [NOTIFICATION_ERROR_CODES.FORBIDDEN_ACCESS]: 403,
    [NOTIFICATION_ERROR_CODES.SERVER_ERROR]: 500,
    [NOTIFICATION_ERROR_CODES.DATABASE_EXCEPTION]: 500,
    [NOTIFICATION_ERROR_CODES.ERROR_FETCHING_NOTIFICATION]: 500,
};

export const EMAIL_ERROR_CODES = {
    EMAIL_NOT_SENT: "EMAIL_NOT_SENT",
    TEMPLATE_RENDER_FAILED: "TEMPLATE_RENDER_FAILED",
    INVALID_EMAIL_ADDRESS: "INVALID_EMAIL_ADDRESS",
    AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
    EMAIL_SERVICE_UNAVAILABLE: "EMAIL_SERVICE_UNAVAILABLE",
};

export const EMAIL_ERROR_MESSAGES = {
    [EMAIL_ERROR_CODES.EMAIL_NOT_SENT]: "The email could not be sent. Please try again later.",
    [EMAIL_ERROR_CODES.TEMPLATE_RENDER_FAILED]: "Failed to render the email template. Please check the template and try again.",
    [EMAIL_ERROR_CODES.INVALID_EMAIL_ADDRESS]: "The provided email address is invalid.",
    [EMAIL_ERROR_CODES.AUTHENTICATION_FAILED]: "Failed to authenticate with the email server.",
    [EMAIL_ERROR_CODES.EMAIL_SERVICE_UNAVAILABLE]: "The email service is currently unavailable. Please try again later.",
};

export const SMS_ERROR_CODES = {
    SMS_NOT_SENT: "SMS_NOT_SENT",
    TEMPLATE_RENDER_FAILED: "TEMPLATE_RENDER_FAILED",
    INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
    AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
    SMS_SERVICE_UNAVAILABLE: "SMS_SERVICE_UNAVAILABLE",
};

export const SMS_ERROR_MESSAGES = {
    [SMS_ERROR_CODES.SMS_NOT_SENT]: "The SMS could not be sent. Please try again later.",
    [SMS_ERROR_CODES.TEMPLATE_RENDER_FAILED]: "Failed to render the SMS template. Please check the template and try again.",
    [SMS_ERROR_CODES.INVALID_PHONE_NUMBER]: "The provided phone number is invalid.",
    [SMS_ERROR_CODES.AUTHENTICATION_FAILED]: "Failed to authenticate with the SMS service provider.",
    [SMS_ERROR_CODES.SMS_SERVICE_UNAVAILABLE]: "The SMS service is currently unavailable. Please try again later.",
};


export const EMAIL_ERROR_STATUS = {
    [EMAIL_ERROR_CODES.EMAIL_NOT_SENT]: 500,
    [EMAIL_ERROR_CODES.TEMPLATE_RENDER_FAILED]: 500,
    [EMAIL_ERROR_CODES.INVALID_EMAIL_ADDRESS]: 400,
    [EMAIL_ERROR_CODES.AUTHENTICATION_FAILED]: 401,
    [EMAIL_ERROR_CODES.EMAIL_SERVICE_UNAVAILABLE]: 503,
};

export const SMS_ERROR_STATUS = {
    [SMS_ERROR_CODES.SMS_NOT_SENT]: 500,
    [SMS_ERROR_CODES.TEMPLATE_RENDER_FAILED]: 500,
    [SMS_ERROR_CODES.INVALID_PHONE_NUMBER]: 400,
    [SMS_ERROR_CODES.AUTHENTICATION_FAILED]: 401,
    [SMS_ERROR_CODES.SMS_SERVICE_UNAVAILABLE]: 503,
};
